name: Github Checks
description: Updates github checks.
author: https://github.com/buildkite
requirements:
  - docker-compose
configuration:
  properties:
    debug:
      type: boolean
    app_id:
      type: str
    private_key:
      type: str
  additionalProperties: false
